### ISSUE TITLE
Why sonar-flutter is so slow ？

### ISSUE THREAD

**Issue by EnPython** [insideapp-oss/sonar-flutter#30]
hi , when i use sonar-scanner to scan my flutter project , i got the confusion that it wasted long time (about 3 hours) to scan my project. But when i use the command line "dartanalyzer lib" to scan my project, it just wasted about 18 min to finish the job. The most confusing is that when i use command line "flutter analyze", it just wasted about 20s to finish the scanned job.
i dont know what is differences among the above tools

**Comment by kuhnroyal** [comment]
Maybe your global dartanalyzer version is older and flutter is using a different one.

The massively extended time on sonar-flutter is something I have noticed as well.
I suspect that it happens because sonar-flutter calls `dartanalyzer` with all the files in the projects as arguments, like `dartanalyzer file1 file2 file3 ...` instead of `dartanalyzer lib test`.
I have created https://github.com/insideapp-oss/sonar-flutter/pull/29 which would allow reusing an existing analyzer report.

**Comment by EnPython** [comment]
hi, i have another questions.
after i reconstructed the scanned engine from dartanalyzer to flutter analyze and use it to scan my flutter project, some confusions comes up. 
The rules like the "null_aware_before_operator", "invalid_use_of_visible_for_testing_member", "null_aware_in_logical_operator" and so on cannot be found in the sonar-flutter ruleset (rules.json). Even if i run the groovy script to update the ruleset, it is not work for matching the flutter analyze scanned result.
So, I would like to confirm if the dart rule base does not match the flutter analyze result or how can i find the flutter analyze ruleset ?
thank you !

**Comment by mreichelt** [comment]
This should be fixed with #46. Now by default `flutter analyze` is used (without arguments), which leads to *much* faster lint scans.
