### ISSUE TITLE
GitHub Action support

### ISSUE THREAD

**Issue by ryan-sf** [insideapp-oss/sonar-flutter#43]
It looks like using this plugin requires a SonarQube server and I'm wondering if that's true and whether it's possible to use this in a GitHub Action?

**Comment by ssulei7** [comment]
This plugin is meant to be used in a Sonarqube server. To integrate with CI, you would need to do a sonar scan within your job that points to your Sonarqube server.

**Comment by iapicca** [comment]
> This plugin is meant to be used in a Sonarqube server. To integrate with CI, you would need to do a sonar scan within your job that points to your Sonarqube server.

I see there's a [docker version](https://hub.docker.com/_/sonarqube) 
is there any reason why wouldn't be possible to use it with github action?

**Comment by ssulei7** [comment]
> > This plugin is meant to be used in a Sonarqube server. To integrate with CI, you would need to do a sonar scan within your job that points to your Sonarqube server.
> 
> I see there's a [docker version](https://hub.docker.com/_/sonarqube)
> is there any reason why wouldn't be possible to use it with github action?

You can use it within Github Actions, I think the point I was making is that you would need to have some level of hosting to see aggregated results of your scans, which requires a SonarQube server. While there is a docker version, yes, you could technically scan your code using a local version of the container (given you build from an image and copy the plugin, and deploy to your container registry of choice). However, the problem is that you're now using a container with an in memory database, hence, when your job completes... that container running will die and you have no way of viewing your results.

My recommendation would be to host that container somewhere where you can tie it back to a SQL Server in your sonar properties file, where the SQL Server would keep record of all of your scans for a particular project.

Check this out, it'll help you get started with a SonarQube server: https://docs.sonarqube.org/latest/setup/install-server/
